[workspace]

members = [
    "examples/convert_rust_json_to_json",
    "examples/ref_vs_borrow",
    "examples/filter_map",
    "examples/serde_jsons",
    "examples/recursion",
    "examples/time_zone_ex",
    "examples/traits",
    "examples/yaml_to_json",
    "examples/two_num",
]