[package]
name = "convert_rust_json_to_json"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
regex = "1.5"
serde_json = "1.0.107"
serde = { version = "1.0.183", features = ["derive"] }
